const productListArray = [
  {
    images: "./1588002143014.jpg",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 4,
    reviews: "(0 reviews)",
  },
  {
    images: "./5da47539c3f9c.jpg",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 2444.80",
    link: "index5.html",
    rating: 5,
    reviews: "(0 reviews)",
  },
  {
    images: "./325daf113fd512d.png",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 25555.80",
    link: "index5.html",
    rating: 2,
    reviews: "(0 reviews)",
  },
  {
    images: "./2075fdcd2dc4e5fd.png",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 6666.80",
    link: "index5.html",
    rating: 4,
    reviews: "(0 reviews)",
  },
  {
    images: "./2075fde5014945f4.png",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 1,
    reviews: "(0 reviews)",
  },
  {
    images: "./2075fe1c0e9db221.png",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 5,
    reviews: "(0 reviews)",
  },
  {
    images: "./6066b995295fa.jpg",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 3,
    reviews: "(0 reviews)",
  },
  {
    images: "./20661b0cb8b103ac.png",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 2,
    reviews: "(0 reviews)",
  },
  {
    images: "./5da47539c3f9c.jpg",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 4,
    reviews: "(0 reviews)",
  },
  {
    images: "./1588002143014.jpg",
    paragraph: "Lorem, ipsum dolor",
    price: "$ 28.80",
    link: "index5.html",
    rating: 5,
    reviews: "(0 reviews)",
  },
];
 
export { productListArray }
// export default productListArray;